// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/exponent/cos_add_1bit1.v
// Created: 2024-05-31 10:33:15
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cos_add_1bit1
// Source Path: exponent/exponent/cos_add_1bit1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cos_add_1bit1
          (clk,
           kill,
           In1,
           x);


  input   clk;
  input   kill;
  input   signed [9:0] In1;  // sfix10_En10
  output  signed [11:0] x;  // sfix12_En10


  wire [9:0] insig_out1;  // ufix10_En10
  wire [17:0] Point25_out1;  // ufix18_En18
  wire [17:0] LTEp25_1_cast;  // ufix18_En18
  wire LTEp25_relop1;
  wire [17:0] Point75_out1;  // ufix18_En18
  wire [17:0] GTEp75_1_cast;  // ufix18_En18
  wire GTEp75_relop1;
  wire alpha1st_or_4th_Quad_bool;
  wire [7:0] alpha1st_or_4th_Quad_out1;  // uint8
  reg [7:0] RAMDelayBalance_reg [0:1];  // ufix8 [2]
  wire [7:0] RAMDelayBalance_reg_next [0:1];  // ufix8 [2]
  wire [7:0] RAMDelayBalance_out1;  // uint8
  wire [17:0] Point50_out1;  // ufix18_En18
  wire [17:0] LTEp50_1_cast;  // ufix18_En18
  wire LTEp50_relop1;
  reg  Unit_Delay6_out1;
  wire signed [18:0] p75mA_sub_cast;  // sfix19_En18
  wire signed [18:0] p75mA_sub_cast_1;  // sfix19_En18
  wire signed [18:0] p75mA_out1;  // sfix19_En18
  reg signed [18:0] Unit_Delay7_out1;  // sfix19_En18
  wire signed [18:0] Amp75_sub_cast;  // sfix19_En18
  wire signed [18:0] Amp75_sub_cast_1;  // sfix19_En18
  wire signed [18:0] Amp75_out1;  // sfix19_En18
  reg  Unit_Delay2_out1;
  wire signed [18:0] Amp25_sub_cast;  // sfix19_En18
  wire signed [18:0] Amp25_sub_cast_1;  // sfix19_En18
  wire signed [18:0] Amp25_out1;  // sfix19_En18
  reg signed [18:0] Unit_Delay3_out1;  // sfix19_En18
  wire signed [18:0] p25mA_sub_cast;  // sfix19_En18
  wire signed [18:0] p25mA_sub_cast_1;  // sfix19_En18
  wire signed [18:0] p25mA_out1;  // sfix19_En18
  reg  Unit_Delay4_out1;
  reg signed [18:0] Unit_Delay5_out1;  // sfix19_En18
  wire signed [18:0] QuadHandle1b_out1;  // sfix19_En18
  wire [9:0] QuadHandle1b_out1_dtc;  // ufix10_En10
  reg signed [18:0] Unit_Delay1_out1;  // sfix19_En18
  wire signed [18:0] QuadHandle1a_out1;  // sfix19_En18
  wire [9:0] QuadHandle1a_out1_dtc;  // ufix10_En10
  wire [9:0] QuadHandle2_out1;  // ufix10_En10
  wire [9:0] CastU16En1_out1;  // ufix10
  wire [10:0] CastU16En3_out1;  // ufix11
  wire [10:0] x4_out1;  // ufix11
  wire [9:0] CastU16En2_out1;  // ufix10
  wire [9:0] Look_Up_Table_k;  // ufix10
  wire signed [11:0] Look_Up_Table_table_data [0:1023];  // sfix12_En10 [1024]
  wire signed [11:0] Look_Up_Table_out1;  // sfix12_En10
  reg signed [11:0] Unit_Delay_out1;  // sfix12_En10
  wire signed [12:0] Negate_cast;  // sfix13_En10
  wire signed [12:0] Negate_cast_1;  // sfix13_En10
  wire signed [11:0] Negate_out1;  // sfix12_En10
  wire signed [11:0] Cosine;  // sfix12_En10

  // saturation block maybe optimized away
  // if the NumDataPoints is a power of 2


  assign insig_out1 = In1;



  assign Point25_out1 = 18'b010000000000000000;



  assign LTEp25_1_cast = {insig_out1, 8'b00000000};
  assign LTEp25_relop1 = LTEp25_1_cast <= Point25_out1;



  assign Point75_out1 = 18'b110000000000000000;



  assign GTEp75_1_cast = {insig_out1, 8'b00000000};
  assign GTEp75_relop1 = GTEp75_1_cast >= Point75_out1;



  assign alpha1st_or_4th_Quad_bool = LTEp25_relop1 | GTEp75_relop1;



  assign alpha1st_or_4th_Quad_out1 = {7'b0, alpha1st_or_4th_Quad_bool};



  always @(posedge clk)
    begin : RAMDelayBalance_process
      if (kill == 1'b1) begin
        RAMDelayBalance_reg[0] <= 8'b00000000;
        RAMDelayBalance_reg[1] <= 8'b00000000;
      end
      else begin
        RAMDelayBalance_reg[0] <= RAMDelayBalance_reg_next[0];
        RAMDelayBalance_reg[1] <= RAMDelayBalance_reg_next[1];
      end
    end

  assign RAMDelayBalance_out1 = RAMDelayBalance_reg[1];
  assign RAMDelayBalance_reg_next[0] = alpha1st_or_4th_Quad_out1;
  assign RAMDelayBalance_reg_next[1] = RAMDelayBalance_reg[0];



  assign Point50_out1 = 18'b100000000000000000;



  assign LTEp50_1_cast = {insig_out1, 8'b00000000};
  assign LTEp50_relop1 = LTEp50_1_cast <= Point50_out1;



  always @(posedge clk)
    begin : Unit_Delay6_process
      if (kill == 1'b1) begin
        Unit_Delay6_out1 <= 1'b0;
      end
      else begin
        Unit_Delay6_out1 <= GTEp75_relop1;
      end
    end



  assign p75mA_sub_cast = {1'b0, Point75_out1};
  assign p75mA_sub_cast_1 = {1'b0, {insig_out1, 8'b00000000}};
  assign p75mA_out1 = p75mA_sub_cast - p75mA_sub_cast_1;



  always @(posedge clk)
    begin : Unit_Delay7_process
      if (kill == 1'b1) begin
        Unit_Delay7_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay7_out1 <= p75mA_out1;
      end
    end



  assign Amp75_sub_cast = {1'b0, {insig_out1, 8'b00000000}};
  assign Amp75_sub_cast_1 = {1'b0, Point75_out1};
  assign Amp75_out1 = Amp75_sub_cast - Amp75_sub_cast_1;



  always @(posedge clk)
    begin : Unit_Delay2_process
      if (kill == 1'b1) begin
        Unit_Delay2_out1 <= 1'b0;
      end
      else begin
        Unit_Delay2_out1 <= LTEp25_relop1;
      end
    end



  assign Amp25_sub_cast = {1'b0, {insig_out1, 8'b00000000}};
  assign Amp25_sub_cast_1 = {1'b0, Point25_out1};
  assign Amp25_out1 = Amp25_sub_cast - Amp25_sub_cast_1;



  always @(posedge clk)
    begin : Unit_Delay3_process
      if (kill == 1'b1) begin
        Unit_Delay3_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay3_out1 <= Amp25_out1;
      end
    end



  assign p25mA_sub_cast = {1'b0, Point25_out1};
  assign p25mA_sub_cast_1 = {1'b0, {insig_out1, 8'b00000000}};
  assign p25mA_out1 = p25mA_sub_cast - p25mA_sub_cast_1;



  always @(posedge clk)
    begin : Unit_Delay4_process
      if (kill == 1'b1) begin
        Unit_Delay4_out1 <= 1'b0;
      end
      else begin
        Unit_Delay4_out1 <= LTEp50_relop1;
      end
    end



  always @(posedge clk)
    begin : Unit_Delay5_process
      if (kill == 1'b1) begin
        Unit_Delay5_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay5_out1 <= Amp75_out1;
      end
    end



  assign QuadHandle1b_out1 = (Unit_Delay6_out1 == 1'b0 ? Unit_Delay7_out1 :
              Unit_Delay5_out1);



  assign QuadHandle1b_out1_dtc = ((QuadHandle1b_out1[18] == 1'b0) && (QuadHandle1b_out1[17:8] == 10'b1111111111) ? 10'b1111111111 :
              (QuadHandle1b_out1[18] == 1'b1 ? 10'b0000000000 :
              QuadHandle1b_out1[17:8]));



  always @(posedge clk)
    begin : Unit_Delay1_process
      if (kill == 1'b1) begin
        Unit_Delay1_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay1_out1 <= p25mA_out1;
      end
    end



  assign QuadHandle1a_out1 = (Unit_Delay2_out1 == 1'b0 ? Unit_Delay3_out1 :
              Unit_Delay1_out1);



  assign QuadHandle1a_out1_dtc = ((QuadHandle1a_out1[18] == 1'b0) && (QuadHandle1a_out1[17:8] == 10'b1111111111) ? 10'b1111111111 :
              (QuadHandle1a_out1[18] == 1'b1 ? 10'b0000000000 :
              QuadHandle1a_out1[17:8]));



  assign QuadHandle2_out1 = (Unit_Delay4_out1 == 1'b0 ? QuadHandle1b_out1_dtc :
              QuadHandle1a_out1_dtc);



  assign CastU16En1_out1 = QuadHandle2_out1;



  assign CastU16En3_out1 = {1'b0, CastU16En1_out1};



  // equivalent to multiply
  // by 4 with saturation
  assign x4_out1 = CastU16En3_out1 <<< 8'd2;



  assign CastU16En2_out1 = (x4_out1[10] != 1'b0 ? 10'b1111111111 :
              x4_out1[9:0]);



  assign Look_Up_Table_table_data[0] = 12'sb000000000000;
  assign Look_Up_Table_table_data[1] = 12'sb000000000001;
  assign Look_Up_Table_table_data[2] = 12'sb000000000011;
  assign Look_Up_Table_table_data[3] = 12'sb000000000100;
  assign Look_Up_Table_table_data[4] = 12'sb000000000110;
  assign Look_Up_Table_table_data[5] = 12'sb000000000111;
  assign Look_Up_Table_table_data[6] = 12'sb000000001001;
  assign Look_Up_Table_table_data[7] = 12'sb000000001011;
  assign Look_Up_Table_table_data[8] = 12'sb000000001100;
  assign Look_Up_Table_table_data[9] = 12'sb000000001110;
  assign Look_Up_Table_table_data[10] = 12'sb000000001111;
  assign Look_Up_Table_table_data[11] = 12'sb000000010001;
  assign Look_Up_Table_table_data[12] = 12'sb000000010010;
  assign Look_Up_Table_table_data[13] = 12'sb000000010100;
  assign Look_Up_Table_table_data[14] = 12'sb000000010110;
  assign Look_Up_Table_table_data[15] = 12'sb000000010111;
  assign Look_Up_Table_table_data[16] = 12'sb000000011001;
  assign Look_Up_Table_table_data[17] = 12'sb000000011010;
  assign Look_Up_Table_table_data[18] = 12'sb000000011100;
  assign Look_Up_Table_table_data[19] = 12'sb000000011101;
  assign Look_Up_Table_table_data[20] = 12'sb000000011111;
  assign Look_Up_Table_table_data[21] = 12'sb000000100001;
  assign Look_Up_Table_table_data[22] = 12'sb000000100010;
  assign Look_Up_Table_table_data[23] = 12'sb000000100100;
  assign Look_Up_Table_table_data[24] = 12'sb000000100101;
  assign Look_Up_Table_table_data[25] = 12'sb000000100111;
  assign Look_Up_Table_table_data[26] = 12'sb000000101000;
  assign Look_Up_Table_table_data[27] = 12'sb000000101010;
  assign Look_Up_Table_table_data[28] = 12'sb000000101100;
  assign Look_Up_Table_table_data[29] = 12'sb000000101101;
  assign Look_Up_Table_table_data[30] = 12'sb000000101111;
  assign Look_Up_Table_table_data[31] = 12'sb000000110000;
  assign Look_Up_Table_table_data[32] = 12'sb000000110010;
  assign Look_Up_Table_table_data[33] = 12'sb000000110011;
  assign Look_Up_Table_table_data[34] = 12'sb000000110101;
  assign Look_Up_Table_table_data[35] = 12'sb000000110111;
  assign Look_Up_Table_table_data[36] = 12'sb000000111000;
  assign Look_Up_Table_table_data[37] = 12'sb000000111010;
  assign Look_Up_Table_table_data[38] = 12'sb000000111011;
  assign Look_Up_Table_table_data[39] = 12'sb000000111101;
  assign Look_Up_Table_table_data[40] = 12'sb000000111110;
  assign Look_Up_Table_table_data[41] = 12'sb000001000000;
  assign Look_Up_Table_table_data[42] = 12'sb000001000001;
  assign Look_Up_Table_table_data[43] = 12'sb000001000011;
  assign Look_Up_Table_table_data[44] = 12'sb000001000101;
  assign Look_Up_Table_table_data[45] = 12'sb000001000110;
  assign Look_Up_Table_table_data[46] = 12'sb000001001000;
  assign Look_Up_Table_table_data[47] = 12'sb000001001001;
  assign Look_Up_Table_table_data[48] = 12'sb000001001011;
  assign Look_Up_Table_table_data[49] = 12'sb000001001100;
  assign Look_Up_Table_table_data[50] = 12'sb000001001110;
  assign Look_Up_Table_table_data[51] = 12'sb000001010000;
  assign Look_Up_Table_table_data[52] = 12'sb000001010001;
  assign Look_Up_Table_table_data[53] = 12'sb000001010011;
  assign Look_Up_Table_table_data[54] = 12'sb000001010100;
  assign Look_Up_Table_table_data[55] = 12'sb000001010110;
  assign Look_Up_Table_table_data[56] = 12'sb000001010111;
  assign Look_Up_Table_table_data[57] = 12'sb000001011001;
  assign Look_Up_Table_table_data[58] = 12'sb000001011011;
  assign Look_Up_Table_table_data[59] = 12'sb000001011100;
  assign Look_Up_Table_table_data[60] = 12'sb000001011110;
  assign Look_Up_Table_table_data[61] = 12'sb000001011111;
  assign Look_Up_Table_table_data[62] = 12'sb000001100001;
  assign Look_Up_Table_table_data[63] = 12'sb000001100010;
  assign Look_Up_Table_table_data[64] = 12'sb000001100100;
  assign Look_Up_Table_table_data[65] = 12'sb000001100110;
  assign Look_Up_Table_table_data[66] = 12'sb000001100111;
  assign Look_Up_Table_table_data[67] = 12'sb000001101001;
  assign Look_Up_Table_table_data[68] = 12'sb000001101010;
  assign Look_Up_Table_table_data[69] = 12'sb000001101100;
  assign Look_Up_Table_table_data[70] = 12'sb000001101101;
  assign Look_Up_Table_table_data[71] = 12'sb000001101111;
  assign Look_Up_Table_table_data[72] = 12'sb000001110000;
  assign Look_Up_Table_table_data[73] = 12'sb000001110010;
  assign Look_Up_Table_table_data[74] = 12'sb000001110100;
  assign Look_Up_Table_table_data[75] = 12'sb000001110101;
  assign Look_Up_Table_table_data[76] = 12'sb000001110111;
  assign Look_Up_Table_table_data[77] = 12'sb000001111000;
  assign Look_Up_Table_table_data[78] = 12'sb000001111010;
  assign Look_Up_Table_table_data[79] = 12'sb000001111011;
  assign Look_Up_Table_table_data[80] = 12'sb000001111101;
  assign Look_Up_Table_table_data[81] = 12'sb000001111111;
  assign Look_Up_Table_table_data[82] = 12'sb000010000000;
  assign Look_Up_Table_table_data[83] = 12'sb000010000010;
  assign Look_Up_Table_table_data[84] = 12'sb000010000011;
  assign Look_Up_Table_table_data[85] = 12'sb000010000101;
  assign Look_Up_Table_table_data[86] = 12'sb000010000110;
  assign Look_Up_Table_table_data[87] = 12'sb000010001000;
  assign Look_Up_Table_table_data[88] = 12'sb000010001001;
  assign Look_Up_Table_table_data[89] = 12'sb000010001011;
  assign Look_Up_Table_table_data[90] = 12'sb000010001101;
  assign Look_Up_Table_table_data[91] = 12'sb000010001110;
  assign Look_Up_Table_table_data[92] = 12'sb000010010000;
  assign Look_Up_Table_table_data[93] = 12'sb000010010001;
  assign Look_Up_Table_table_data[94] = 12'sb000010010011;
  assign Look_Up_Table_table_data[95] = 12'sb000010010100;
  assign Look_Up_Table_table_data[96] = 12'sb000010010110;
  assign Look_Up_Table_table_data[97] = 12'sb000010010111;
  assign Look_Up_Table_table_data[98] = 12'sb000010011001;
  assign Look_Up_Table_table_data[99] = 12'sb000010011011;
  assign Look_Up_Table_table_data[100] = 12'sb000010011100;
  assign Look_Up_Table_table_data[101] = 12'sb000010011110;
  assign Look_Up_Table_table_data[102] = 12'sb000010011111;
  assign Look_Up_Table_table_data[103] = 12'sb000010100001;
  assign Look_Up_Table_table_data[104] = 12'sb000010100010;
  assign Look_Up_Table_table_data[105] = 12'sb000010100100;
  assign Look_Up_Table_table_data[106] = 12'sb000010100101;
  assign Look_Up_Table_table_data[107] = 12'sb000010100111;
  assign Look_Up_Table_table_data[108] = 12'sb000010101001;
  assign Look_Up_Table_table_data[109] = 12'sb000010101010;
  assign Look_Up_Table_table_data[110] = 12'sb000010101100;
  assign Look_Up_Table_table_data[111] = 12'sb000010101101;
  assign Look_Up_Table_table_data[112] = 12'sb000010101111;
  assign Look_Up_Table_table_data[113] = 12'sb000010110000;
  assign Look_Up_Table_table_data[114] = 12'sb000010110010;
  assign Look_Up_Table_table_data[115] = 12'sb000010110011;
  assign Look_Up_Table_table_data[116] = 12'sb000010110101;
  assign Look_Up_Table_table_data[117] = 12'sb000010110110;
  assign Look_Up_Table_table_data[118] = 12'sb000010111000;
  assign Look_Up_Table_table_data[119] = 12'sb000010111010;
  assign Look_Up_Table_table_data[120] = 12'sb000010111011;
  assign Look_Up_Table_table_data[121] = 12'sb000010111101;
  assign Look_Up_Table_table_data[122] = 12'sb000010111110;
  assign Look_Up_Table_table_data[123] = 12'sb000011000000;
  assign Look_Up_Table_table_data[124] = 12'sb000011000001;
  assign Look_Up_Table_table_data[125] = 12'sb000011000011;
  assign Look_Up_Table_table_data[126] = 12'sb000011000100;
  assign Look_Up_Table_table_data[127] = 12'sb000011000110;
  assign Look_Up_Table_table_data[128] = 12'sb000011000111;
  assign Look_Up_Table_table_data[129] = 12'sb000011001001;
  assign Look_Up_Table_table_data[130] = 12'sb000011001011;
  assign Look_Up_Table_table_data[131] = 12'sb000011001100;
  assign Look_Up_Table_table_data[132] = 12'sb000011001110;
  assign Look_Up_Table_table_data[133] = 12'sb000011001111;
  assign Look_Up_Table_table_data[134] = 12'sb000011010001;
  assign Look_Up_Table_table_data[135] = 12'sb000011010010;
  assign Look_Up_Table_table_data[136] = 12'sb000011010100;
  assign Look_Up_Table_table_data[137] = 12'sb000011010101;
  assign Look_Up_Table_table_data[138] = 12'sb000011010111;
  assign Look_Up_Table_table_data[139] = 12'sb000011011000;
  assign Look_Up_Table_table_data[140] = 12'sb000011011010;
  assign Look_Up_Table_table_data[141] = 12'sb000011011011;
  assign Look_Up_Table_table_data[142] = 12'sb000011011101;
  assign Look_Up_Table_table_data[143] = 12'sb000011011111;
  assign Look_Up_Table_table_data[144] = 12'sb000011100000;
  assign Look_Up_Table_table_data[145] = 12'sb000011100010;
  assign Look_Up_Table_table_data[146] = 12'sb000011100011;
  assign Look_Up_Table_table_data[147] = 12'sb000011100101;
  assign Look_Up_Table_table_data[148] = 12'sb000011100110;
  assign Look_Up_Table_table_data[149] = 12'sb000011101000;
  assign Look_Up_Table_table_data[150] = 12'sb000011101001;
  assign Look_Up_Table_table_data[151] = 12'sb000011101011;
  assign Look_Up_Table_table_data[152] = 12'sb000011101100;
  assign Look_Up_Table_table_data[153] = 12'sb000011101110;
  assign Look_Up_Table_table_data[154] = 12'sb000011101111;
  assign Look_Up_Table_table_data[155] = 12'sb000011110001;
  assign Look_Up_Table_table_data[156] = 12'sb000011110010;
  assign Look_Up_Table_table_data[157] = 12'sb000011110100;
  assign Look_Up_Table_table_data[158] = 12'sb000011110101;
  assign Look_Up_Table_table_data[159] = 12'sb000011110111;
  assign Look_Up_Table_table_data[160] = 12'sb000011111001;
  assign Look_Up_Table_table_data[161] = 12'sb000011111010;
  assign Look_Up_Table_table_data[162] = 12'sb000011111100;
  assign Look_Up_Table_table_data[163] = 12'sb000011111101;
  assign Look_Up_Table_table_data[164] = 12'sb000011111111;
  assign Look_Up_Table_table_data[165] = 12'sb000100000000;
  assign Look_Up_Table_table_data[166] = 12'sb000100000010;
  assign Look_Up_Table_table_data[167] = 12'sb000100000011;
  assign Look_Up_Table_table_data[168] = 12'sb000100000101;
  assign Look_Up_Table_table_data[169] = 12'sb000100000110;
  assign Look_Up_Table_table_data[170] = 12'sb000100001000;
  assign Look_Up_Table_table_data[171] = 12'sb000100001001;
  assign Look_Up_Table_table_data[172] = 12'sb000100001011;
  assign Look_Up_Table_table_data[173] = 12'sb000100001100;
  assign Look_Up_Table_table_data[174] = 12'sb000100001110;
  assign Look_Up_Table_table_data[175] = 12'sb000100001111;
  assign Look_Up_Table_table_data[176] = 12'sb000100010001;
  assign Look_Up_Table_table_data[177] = 12'sb000100010010;
  assign Look_Up_Table_table_data[178] = 12'sb000100010100;
  assign Look_Up_Table_table_data[179] = 12'sb000100010101;
  assign Look_Up_Table_table_data[180] = 12'sb000100010111;
  assign Look_Up_Table_table_data[181] = 12'sb000100011000;
  assign Look_Up_Table_table_data[182] = 12'sb000100011010;
  assign Look_Up_Table_table_data[183] = 12'sb000100011011;
  assign Look_Up_Table_table_data[184] = 12'sb000100011101;
  assign Look_Up_Table_table_data[185] = 12'sb000100011110;
  assign Look_Up_Table_table_data[186] = 12'sb000100100000;
  assign Look_Up_Table_table_data[187] = 12'sb000100100010;
  assign Look_Up_Table_table_data[188] = 12'sb000100100011;
  assign Look_Up_Table_table_data[189] = 12'sb000100100101;
  assign Look_Up_Table_table_data[190] = 12'sb000100100110;
  assign Look_Up_Table_table_data[191] = 12'sb000100101000;
  assign Look_Up_Table_table_data[192] = 12'sb000100101001;
  assign Look_Up_Table_table_data[193] = 12'sb000100101011;
  assign Look_Up_Table_table_data[194] = 12'sb000100101100;
  assign Look_Up_Table_table_data[195] = 12'sb000100101110;
  assign Look_Up_Table_table_data[196] = 12'sb000100101111;
  assign Look_Up_Table_table_data[197] = 12'sb000100110001;
  assign Look_Up_Table_table_data[198] = 12'sb000100110010;
  assign Look_Up_Table_table_data[199] = 12'sb000100110100;
  assign Look_Up_Table_table_data[200] = 12'sb000100110101;
  assign Look_Up_Table_table_data[201] = 12'sb000100110111;
  assign Look_Up_Table_table_data[202] = 12'sb000100111000;
  assign Look_Up_Table_table_data[203] = 12'sb000100111010;
  assign Look_Up_Table_table_data[204] = 12'sb000100111011;
  assign Look_Up_Table_table_data[205] = 12'sb000100111101;
  assign Look_Up_Table_table_data[206] = 12'sb000100111110;
  assign Look_Up_Table_table_data[207] = 12'sb000101000000;
  assign Look_Up_Table_table_data[208] = 12'sb000101000001;
  assign Look_Up_Table_table_data[209] = 12'sb000101000011;
  assign Look_Up_Table_table_data[210] = 12'sb000101000100;
  assign Look_Up_Table_table_data[211] = 12'sb000101000101;
  assign Look_Up_Table_table_data[212] = 12'sb000101000111;
  assign Look_Up_Table_table_data[213] = 12'sb000101001000;
  assign Look_Up_Table_table_data[214] = 12'sb000101001010;
  assign Look_Up_Table_table_data[215] = 12'sb000101001011;
  assign Look_Up_Table_table_data[216] = 12'sb000101001101;
  assign Look_Up_Table_table_data[217] = 12'sb000101001110;
  assign Look_Up_Table_table_data[218] = 12'sb000101010000;
  assign Look_Up_Table_table_data[219] = 12'sb000101010001;
  assign Look_Up_Table_table_data[220] = 12'sb000101010011;
  assign Look_Up_Table_table_data[221] = 12'sb000101010100;
  assign Look_Up_Table_table_data[222] = 12'sb000101010110;
  assign Look_Up_Table_table_data[223] = 12'sb000101010111;
  assign Look_Up_Table_table_data[224] = 12'sb000101011001;
  assign Look_Up_Table_table_data[225] = 12'sb000101011010;
  assign Look_Up_Table_table_data[226] = 12'sb000101011100;
  assign Look_Up_Table_table_data[227] = 12'sb000101011101;
  assign Look_Up_Table_table_data[228] = 12'sb000101011111;
  assign Look_Up_Table_table_data[229] = 12'sb000101100000;
  assign Look_Up_Table_table_data[230] = 12'sb000101100010;
  assign Look_Up_Table_table_data[231] = 12'sb000101100011;
  assign Look_Up_Table_table_data[232] = 12'sb000101100101;
  assign Look_Up_Table_table_data[233] = 12'sb000101100110;
  assign Look_Up_Table_table_data[234] = 12'sb000101101000;
  assign Look_Up_Table_table_data[235] = 12'sb000101101001;
  assign Look_Up_Table_table_data[236] = 12'sb000101101011;
  assign Look_Up_Table_table_data[237] = 12'sb000101101100;
  assign Look_Up_Table_table_data[238] = 12'sb000101101101;
  assign Look_Up_Table_table_data[239] = 12'sb000101101111;
  assign Look_Up_Table_table_data[240] = 12'sb000101110000;
  assign Look_Up_Table_table_data[241] = 12'sb000101110010;
  assign Look_Up_Table_table_data[242] = 12'sb000101110011;
  assign Look_Up_Table_table_data[243] = 12'sb000101110101;
  assign Look_Up_Table_table_data[244] = 12'sb000101110110;
  assign Look_Up_Table_table_data[245] = 12'sb000101111000;
  assign Look_Up_Table_table_data[246] = 12'sb000101111001;
  assign Look_Up_Table_table_data[247] = 12'sb000101111011;
  assign Look_Up_Table_table_data[248] = 12'sb000101111100;
  assign Look_Up_Table_table_data[249] = 12'sb000101111110;
  assign Look_Up_Table_table_data[250] = 12'sb000101111111;
  assign Look_Up_Table_table_data[251] = 12'sb000110000000;
  assign Look_Up_Table_table_data[252] = 12'sb000110000010;
  assign Look_Up_Table_table_data[253] = 12'sb000110000011;
  assign Look_Up_Table_table_data[254] = 12'sb000110000101;
  assign Look_Up_Table_table_data[255] = 12'sb000110000110;
  assign Look_Up_Table_table_data[256] = 12'sb000110001000;
  assign Look_Up_Table_table_data[257] = 12'sb000110001001;
  assign Look_Up_Table_table_data[258] = 12'sb000110001011;
  assign Look_Up_Table_table_data[259] = 12'sb000110001100;
  assign Look_Up_Table_table_data[260] = 12'sb000110001110;
  assign Look_Up_Table_table_data[261] = 12'sb000110001111;
  assign Look_Up_Table_table_data[262] = 12'sb000110010000;
  assign Look_Up_Table_table_data[263] = 12'sb000110010010;
  assign Look_Up_Table_table_data[264] = 12'sb000110010011;
  assign Look_Up_Table_table_data[265] = 12'sb000110010101;
  assign Look_Up_Table_table_data[266] = 12'sb000110010110;
  assign Look_Up_Table_table_data[267] = 12'sb000110011000;
  assign Look_Up_Table_table_data[268] = 12'sb000110011001;
  assign Look_Up_Table_table_data[269] = 12'sb000110011011;
  assign Look_Up_Table_table_data[270] = 12'sb000110011100;
  assign Look_Up_Table_table_data[271] = 12'sb000110011101;
  assign Look_Up_Table_table_data[272] = 12'sb000110011111;
  assign Look_Up_Table_table_data[273] = 12'sb000110100000;
  assign Look_Up_Table_table_data[274] = 12'sb000110100010;
  assign Look_Up_Table_table_data[275] = 12'sb000110100011;
  assign Look_Up_Table_table_data[276] = 12'sb000110100101;
  assign Look_Up_Table_table_data[277] = 12'sb000110100110;
  assign Look_Up_Table_table_data[278] = 12'sb000110100111;
  assign Look_Up_Table_table_data[279] = 12'sb000110101001;
  assign Look_Up_Table_table_data[280] = 12'sb000110101010;
  assign Look_Up_Table_table_data[281] = 12'sb000110101100;
  assign Look_Up_Table_table_data[282] = 12'sb000110101101;
  assign Look_Up_Table_table_data[283] = 12'sb000110101111;
  assign Look_Up_Table_table_data[284] = 12'sb000110110000;
  assign Look_Up_Table_table_data[285] = 12'sb000110110001;
  assign Look_Up_Table_table_data[286] = 12'sb000110110011;
  assign Look_Up_Table_table_data[287] = 12'sb000110110100;
  assign Look_Up_Table_table_data[288] = 12'sb000110110110;
  assign Look_Up_Table_table_data[289] = 12'sb000110110111;
  assign Look_Up_Table_table_data[290] = 12'sb000110111001;
  assign Look_Up_Table_table_data[291] = 12'sb000110111010;
  assign Look_Up_Table_table_data[292] = 12'sb000110111011;
  assign Look_Up_Table_table_data[293] = 12'sb000110111101;
  assign Look_Up_Table_table_data[294] = 12'sb000110111110;
  assign Look_Up_Table_table_data[295] = 12'sb000111000000;
  assign Look_Up_Table_table_data[296] = 12'sb000111000001;
  assign Look_Up_Table_table_data[297] = 12'sb000111000010;
  assign Look_Up_Table_table_data[298] = 12'sb000111000100;
  assign Look_Up_Table_table_data[299] = 12'sb000111000101;
  assign Look_Up_Table_table_data[300] = 12'sb000111000111;
  assign Look_Up_Table_table_data[301] = 12'sb000111001000;
  assign Look_Up_Table_table_data[302] = 12'sb000111001010;
  assign Look_Up_Table_table_data[303] = 12'sb000111001011;
  assign Look_Up_Table_table_data[304] = 12'sb000111001100;
  assign Look_Up_Table_table_data[305] = 12'sb000111001110;
  assign Look_Up_Table_table_data[306] = 12'sb000111001111;
  assign Look_Up_Table_table_data[307] = 12'sb000111010001;
  assign Look_Up_Table_table_data[308] = 12'sb000111010010;
  assign Look_Up_Table_table_data[309] = 12'sb000111010011;
  assign Look_Up_Table_table_data[310] = 12'sb000111010101;
  assign Look_Up_Table_table_data[311] = 12'sb000111010110;
  assign Look_Up_Table_table_data[312] = 12'sb000111011000;
  assign Look_Up_Table_table_data[313] = 12'sb000111011001;
  assign Look_Up_Table_table_data[314] = 12'sb000111011010;
  assign Look_Up_Table_table_data[315] = 12'sb000111011100;
  assign Look_Up_Table_table_data[316] = 12'sb000111011101;
  assign Look_Up_Table_table_data[317] = 12'sb000111011110;
  assign Look_Up_Table_table_data[318] = 12'sb000111100000;
  assign Look_Up_Table_table_data[319] = 12'sb000111100001;
  assign Look_Up_Table_table_data[320] = 12'sb000111100011;
  assign Look_Up_Table_table_data[321] = 12'sb000111100100;
  assign Look_Up_Table_table_data[322] = 12'sb000111100101;
  assign Look_Up_Table_table_data[323] = 12'sb000111100111;
  assign Look_Up_Table_table_data[324] = 12'sb000111101000;
  assign Look_Up_Table_table_data[325] = 12'sb000111101010;
  assign Look_Up_Table_table_data[326] = 12'sb000111101011;
  assign Look_Up_Table_table_data[327] = 12'sb000111101100;
  assign Look_Up_Table_table_data[328] = 12'sb000111101110;
  assign Look_Up_Table_table_data[329] = 12'sb000111101111;
  assign Look_Up_Table_table_data[330] = 12'sb000111110000;
  assign Look_Up_Table_table_data[331] = 12'sb000111110010;
  assign Look_Up_Table_table_data[332] = 12'sb000111110011;
  assign Look_Up_Table_table_data[333] = 12'sb000111110101;
  assign Look_Up_Table_table_data[334] = 12'sb000111110110;
  assign Look_Up_Table_table_data[335] = 12'sb000111110111;
  assign Look_Up_Table_table_data[336] = 12'sb000111111001;
  assign Look_Up_Table_table_data[337] = 12'sb000111111010;
  assign Look_Up_Table_table_data[338] = 12'sb000111111011;
  assign Look_Up_Table_table_data[339] = 12'sb000111111101;
  assign Look_Up_Table_table_data[340] = 12'sb000111111110;
  assign Look_Up_Table_table_data[341] = 12'sb001000000000;
  assign Look_Up_Table_table_data[342] = 12'sb001000000001;
  assign Look_Up_Table_table_data[343] = 12'sb001000000010;
  assign Look_Up_Table_table_data[344] = 12'sb001000000100;
  assign Look_Up_Table_table_data[345] = 12'sb001000000101;
  assign Look_Up_Table_table_data[346] = 12'sb001000000110;
  assign Look_Up_Table_table_data[347] = 12'sb001000001000;
  assign Look_Up_Table_table_data[348] = 12'sb001000001001;
  assign Look_Up_Table_table_data[349] = 12'sb001000001010;
  assign Look_Up_Table_table_data[350] = 12'sb001000001100;
  assign Look_Up_Table_table_data[351] = 12'sb001000001101;
  assign Look_Up_Table_table_data[352] = 12'sb001000001110;
  assign Look_Up_Table_table_data[353] = 12'sb001000010000;
  assign Look_Up_Table_table_data[354] = 12'sb001000010001;
  assign Look_Up_Table_table_data[355] = 12'sb001000010010;
  assign Look_Up_Table_table_data[356] = 12'sb001000010100;
  assign Look_Up_Table_table_data[357] = 12'sb001000010101;
  assign Look_Up_Table_table_data[358] = 12'sb001000010110;
  assign Look_Up_Table_table_data[359] = 12'sb001000011000;
  assign Look_Up_Table_table_data[360] = 12'sb001000011001;
  assign Look_Up_Table_table_data[361] = 12'sb001000011010;
  assign Look_Up_Table_table_data[362] = 12'sb001000011100;
  assign Look_Up_Table_table_data[363] = 12'sb001000011101;
  assign Look_Up_Table_table_data[364] = 12'sb001000011110;
  assign Look_Up_Table_table_data[365] = 12'sb001000100000;
  assign Look_Up_Table_table_data[366] = 12'sb001000100001;
  assign Look_Up_Table_table_data[367] = 12'sb001000100010;
  assign Look_Up_Table_table_data[368] = 12'sb001000100100;
  assign Look_Up_Table_table_data[369] = 12'sb001000100101;
  assign Look_Up_Table_table_data[370] = 12'sb001000100110;
  assign Look_Up_Table_table_data[371] = 12'sb001000101000;
  assign Look_Up_Table_table_data[372] = 12'sb001000101001;
  assign Look_Up_Table_table_data[373] = 12'sb001000101010;
  assign Look_Up_Table_table_data[374] = 12'sb001000101100;
  assign Look_Up_Table_table_data[375] = 12'sb001000101101;
  assign Look_Up_Table_table_data[376] = 12'sb001000101110;
  assign Look_Up_Table_table_data[377] = 12'sb001000110000;
  assign Look_Up_Table_table_data[378] = 12'sb001000110001;
  assign Look_Up_Table_table_data[379] = 12'sb001000110010;
  assign Look_Up_Table_table_data[380] = 12'sb001000110100;
  assign Look_Up_Table_table_data[381] = 12'sb001000110101;
  assign Look_Up_Table_table_data[382] = 12'sb001000110110;
  assign Look_Up_Table_table_data[383] = 12'sb001000111000;
  assign Look_Up_Table_table_data[384] = 12'sb001000111001;
  assign Look_Up_Table_table_data[385] = 12'sb001000111010;
  assign Look_Up_Table_table_data[386] = 12'sb001000111100;
  assign Look_Up_Table_table_data[387] = 12'sb001000111101;
  assign Look_Up_Table_table_data[388] = 12'sb001000111110;
  assign Look_Up_Table_table_data[389] = 12'sb001000111111;
  assign Look_Up_Table_table_data[390] = 12'sb001001000001;
  assign Look_Up_Table_table_data[391] = 12'sb001001000010;
  assign Look_Up_Table_table_data[392] = 12'sb001001000011;
  assign Look_Up_Table_table_data[393] = 12'sb001001000101;
  assign Look_Up_Table_table_data[394] = 12'sb001001000110;
  assign Look_Up_Table_table_data[395] = 12'sb001001000111;
  assign Look_Up_Table_table_data[396] = 12'sb001001001000;
  assign Look_Up_Table_table_data[397] = 12'sb001001001010;
  assign Look_Up_Table_table_data[398] = 12'sb001001001011;
  assign Look_Up_Table_table_data[399] = 12'sb001001001100;
  assign Look_Up_Table_table_data[400] = 12'sb001001001110;
  assign Look_Up_Table_table_data[401] = 12'sb001001001111;
  assign Look_Up_Table_table_data[402] = 12'sb001001010000;
  assign Look_Up_Table_table_data[403] = 12'sb001001010001;
  assign Look_Up_Table_table_data[404] = 12'sb001001010011;
  assign Look_Up_Table_table_data[405] = 12'sb001001010100;
  assign Look_Up_Table_table_data[406] = 12'sb001001010101;
  assign Look_Up_Table_table_data[407] = 12'sb001001010111;
  assign Look_Up_Table_table_data[408] = 12'sb001001011000;
  assign Look_Up_Table_table_data[409] = 12'sb001001011001;
  assign Look_Up_Table_table_data[410] = 12'sb001001011010;
  assign Look_Up_Table_table_data[411] = 12'sb001001011100;
  assign Look_Up_Table_table_data[412] = 12'sb001001011101;
  assign Look_Up_Table_table_data[413] = 12'sb001001011110;
  assign Look_Up_Table_table_data[414] = 12'sb001001011111;
  assign Look_Up_Table_table_data[415] = 12'sb001001100001;
  assign Look_Up_Table_table_data[416] = 12'sb001001100010;
  assign Look_Up_Table_table_data[417] = 12'sb001001100011;
  assign Look_Up_Table_table_data[418] = 12'sb001001100101;
  assign Look_Up_Table_table_data[419] = 12'sb001001100110;
  assign Look_Up_Table_table_data[420] = 12'sb001001100111;
  assign Look_Up_Table_table_data[421] = 12'sb001001101000;
  assign Look_Up_Table_table_data[422] = 12'sb001001101010;
  assign Look_Up_Table_table_data[423] = 12'sb001001101011;
  assign Look_Up_Table_table_data[424] = 12'sb001001101100;
  assign Look_Up_Table_table_data[425] = 12'sb001001101101;
  assign Look_Up_Table_table_data[426] = 12'sb001001101111;
  assign Look_Up_Table_table_data[427] = 12'sb001001110000;
  assign Look_Up_Table_table_data[428] = 12'sb001001110001;
  assign Look_Up_Table_table_data[429] = 12'sb001001110010;
  assign Look_Up_Table_table_data[430] = 12'sb001001110100;
  assign Look_Up_Table_table_data[431] = 12'sb001001110101;
  assign Look_Up_Table_table_data[432] = 12'sb001001110110;
  assign Look_Up_Table_table_data[433] = 12'sb001001110111;
  assign Look_Up_Table_table_data[434] = 12'sb001001111000;
  assign Look_Up_Table_table_data[435] = 12'sb001001111010;
  assign Look_Up_Table_table_data[436] = 12'sb001001111011;
  assign Look_Up_Table_table_data[437] = 12'sb001001111100;
  assign Look_Up_Table_table_data[438] = 12'sb001001111101;
  assign Look_Up_Table_table_data[439] = 12'sb001001111111;
  assign Look_Up_Table_table_data[440] = 12'sb001010000000;
  assign Look_Up_Table_table_data[441] = 12'sb001010000001;
  assign Look_Up_Table_table_data[442] = 12'sb001010000010;
  assign Look_Up_Table_table_data[443] = 12'sb001010000100;
  assign Look_Up_Table_table_data[444] = 12'sb001010000101;
  assign Look_Up_Table_table_data[445] = 12'sb001010000110;
  assign Look_Up_Table_table_data[446] = 12'sb001010000111;
  assign Look_Up_Table_table_data[447] = 12'sb001010001000;
  assign Look_Up_Table_table_data[448] = 12'sb001010001010;
  assign Look_Up_Table_table_data[449] = 12'sb001010001011;
  assign Look_Up_Table_table_data[450] = 12'sb001010001100;
  assign Look_Up_Table_table_data[451] = 12'sb001010001101;
  assign Look_Up_Table_table_data[452] = 12'sb001010001110;
  assign Look_Up_Table_table_data[453] = 12'sb001010010000;
  assign Look_Up_Table_table_data[454] = 12'sb001010010001;
  assign Look_Up_Table_table_data[455] = 12'sb001010010010;
  assign Look_Up_Table_table_data[456] = 12'sb001010010011;
  assign Look_Up_Table_table_data[457] = 12'sb001010010101;
  assign Look_Up_Table_table_data[458] = 12'sb001010010110;
  assign Look_Up_Table_table_data[459] = 12'sb001010010111;
  assign Look_Up_Table_table_data[460] = 12'sb001010011000;
  assign Look_Up_Table_table_data[461] = 12'sb001010011001;
  assign Look_Up_Table_table_data[462] = 12'sb001010011011;
  assign Look_Up_Table_table_data[463] = 12'sb001010011100;
  assign Look_Up_Table_table_data[464] = 12'sb001010011101;
  assign Look_Up_Table_table_data[465] = 12'sb001010011110;
  assign Look_Up_Table_table_data[466] = 12'sb001010011111;
  assign Look_Up_Table_table_data[467] = 12'sb001010100000;
  assign Look_Up_Table_table_data[468] = 12'sb001010100010;
  assign Look_Up_Table_table_data[469] = 12'sb001010100011;
  assign Look_Up_Table_table_data[470] = 12'sb001010100100;
  assign Look_Up_Table_table_data[471] = 12'sb001010100101;
  assign Look_Up_Table_table_data[472] = 12'sb001010100110;
  assign Look_Up_Table_table_data[473] = 12'sb001010101000;
  assign Look_Up_Table_table_data[474] = 12'sb001010101001;
  assign Look_Up_Table_table_data[475] = 12'sb001010101010;
  assign Look_Up_Table_table_data[476] = 12'sb001010101011;
  assign Look_Up_Table_table_data[477] = 12'sb001010101100;
  assign Look_Up_Table_table_data[478] = 12'sb001010101101;
  assign Look_Up_Table_table_data[479] = 12'sb001010101111;
  assign Look_Up_Table_table_data[480] = 12'sb001010110000;
  assign Look_Up_Table_table_data[481] = 12'sb001010110001;
  assign Look_Up_Table_table_data[482] = 12'sb001010110010;
  assign Look_Up_Table_table_data[483] = 12'sb001010110011;
  assign Look_Up_Table_table_data[484] = 12'sb001010110100;
  assign Look_Up_Table_table_data[485] = 12'sb001010110110;
  assign Look_Up_Table_table_data[486] = 12'sb001010110111;
  assign Look_Up_Table_table_data[487] = 12'sb001010111000;
  assign Look_Up_Table_table_data[488] = 12'sb001010111001;
  assign Look_Up_Table_table_data[489] = 12'sb001010111010;
  assign Look_Up_Table_table_data[490] = 12'sb001010111011;
  assign Look_Up_Table_table_data[491] = 12'sb001010111100;
  assign Look_Up_Table_table_data[492] = 12'sb001010111110;
  assign Look_Up_Table_table_data[493] = 12'sb001010111111;
  assign Look_Up_Table_table_data[494] = 12'sb001011000000;
  assign Look_Up_Table_table_data[495] = 12'sb001011000001;
  assign Look_Up_Table_table_data[496] = 12'sb001011000010;
  assign Look_Up_Table_table_data[497] = 12'sb001011000011;
  assign Look_Up_Table_table_data[498] = 12'sb001011000100;
  assign Look_Up_Table_table_data[499] = 12'sb001011000110;
  assign Look_Up_Table_table_data[500] = 12'sb001011000111;
  assign Look_Up_Table_table_data[501] = 12'sb001011001000;
  assign Look_Up_Table_table_data[502] = 12'sb001011001001;
  assign Look_Up_Table_table_data[503] = 12'sb001011001010;
  assign Look_Up_Table_table_data[504] = 12'sb001011001011;
  assign Look_Up_Table_table_data[505] = 12'sb001011001100;
  assign Look_Up_Table_table_data[506] = 12'sb001011001101;
  assign Look_Up_Table_table_data[507] = 12'sb001011001111;
  assign Look_Up_Table_table_data[508] = 12'sb001011010000;
  assign Look_Up_Table_table_data[509] = 12'sb001011010001;
  assign Look_Up_Table_table_data[510] = 12'sb001011010010;
  assign Look_Up_Table_table_data[511] = 12'sb001011010011;
  assign Look_Up_Table_table_data[512] = 12'sb001011010100;
  assign Look_Up_Table_table_data[513] = 12'sb001011010101;
  assign Look_Up_Table_table_data[514] = 12'sb001011010110;
  assign Look_Up_Table_table_data[515] = 12'sb001011010111;
  assign Look_Up_Table_table_data[516] = 12'sb001011011001;
  assign Look_Up_Table_table_data[517] = 12'sb001011011010;
  assign Look_Up_Table_table_data[518] = 12'sb001011011011;
  assign Look_Up_Table_table_data[519] = 12'sb001011011100;
  assign Look_Up_Table_table_data[520] = 12'sb001011011101;
  assign Look_Up_Table_table_data[521] = 12'sb001011011110;
  assign Look_Up_Table_table_data[522] = 12'sb001011011111;
  assign Look_Up_Table_table_data[523] = 12'sb001011100000;
  assign Look_Up_Table_table_data[524] = 12'sb001011100001;
  assign Look_Up_Table_table_data[525] = 12'sb001011100010;
  assign Look_Up_Table_table_data[526] = 12'sb001011100100;
  assign Look_Up_Table_table_data[527] = 12'sb001011100101;
  assign Look_Up_Table_table_data[528] = 12'sb001011100110;
  assign Look_Up_Table_table_data[529] = 12'sb001011100111;
  assign Look_Up_Table_table_data[530] = 12'sb001011101000;
  assign Look_Up_Table_table_data[531] = 12'sb001011101001;
  assign Look_Up_Table_table_data[532] = 12'sb001011101010;
  assign Look_Up_Table_table_data[533] = 12'sb001011101011;
  assign Look_Up_Table_table_data[534] = 12'sb001011101100;
  assign Look_Up_Table_table_data[535] = 12'sb001011101101;
  assign Look_Up_Table_table_data[536] = 12'sb001011101110;
  assign Look_Up_Table_table_data[537] = 12'sb001011101111;
  assign Look_Up_Table_table_data[538] = 12'sb001011110000;
  assign Look_Up_Table_table_data[539] = 12'sb001011110001;
  assign Look_Up_Table_table_data[540] = 12'sb001011110011;
  assign Look_Up_Table_table_data[541] = 12'sb001011110100;
  assign Look_Up_Table_table_data[542] = 12'sb001011110101;
  assign Look_Up_Table_table_data[543] = 12'sb001011110110;
  assign Look_Up_Table_table_data[544] = 12'sb001011110111;
  assign Look_Up_Table_table_data[545] = 12'sb001011111000;
  assign Look_Up_Table_table_data[546] = 12'sb001011111001;
  assign Look_Up_Table_table_data[547] = 12'sb001011111010;
  assign Look_Up_Table_table_data[548] = 12'sb001011111011;
  assign Look_Up_Table_table_data[549] = 12'sb001011111100;
  assign Look_Up_Table_table_data[550] = 12'sb001011111101;
  assign Look_Up_Table_table_data[551] = 12'sb001011111110;
  assign Look_Up_Table_table_data[552] = 12'sb001011111111;
  assign Look_Up_Table_table_data[553] = 12'sb001100000000;
  assign Look_Up_Table_table_data[554] = 12'sb001100000001;
  assign Look_Up_Table_table_data[555] = 12'sb001100000010;
  assign Look_Up_Table_table_data[556] = 12'sb001100000011;
  assign Look_Up_Table_table_data[557] = 12'sb001100000100;
  assign Look_Up_Table_table_data[558] = 12'sb001100000101;
  assign Look_Up_Table_table_data[559] = 12'sb001100000110;
  assign Look_Up_Table_table_data[560] = 12'sb001100000111;
  assign Look_Up_Table_table_data[561] = 12'sb001100001000;
  assign Look_Up_Table_table_data[562] = 12'sb001100001001;
  assign Look_Up_Table_table_data[563] = 12'sb001100001011;
  assign Look_Up_Table_table_data[564] = 12'sb001100001100;
  assign Look_Up_Table_table_data[565] = 12'sb001100001101;
  assign Look_Up_Table_table_data[566] = 12'sb001100001110;
  assign Look_Up_Table_table_data[567] = 12'sb001100001111;
  assign Look_Up_Table_table_data[568] = 12'sb001100010000;
  assign Look_Up_Table_table_data[569] = 12'sb001100010001;
  assign Look_Up_Table_table_data[570] = 12'sb001100010010;
  assign Look_Up_Table_table_data[571] = 12'sb001100010011;
  assign Look_Up_Table_table_data[572] = 12'sb001100010100;
  assign Look_Up_Table_table_data[573] = 12'sb001100010101;
  assign Look_Up_Table_table_data[574] = 12'sb001100010110;
  assign Look_Up_Table_table_data[575] = 12'sb001100010111;
  assign Look_Up_Table_table_data[576] = 12'sb001100011000;
  assign Look_Up_Table_table_data[577] = 12'sb001100011001;
  assign Look_Up_Table_table_data[578] = 12'sb001100011010;
  assign Look_Up_Table_table_data[579] = 12'sb001100011011;
  assign Look_Up_Table_table_data[580] = 12'sb001100011100;
  assign Look_Up_Table_table_data[581] = 12'sb001100011101;
  assign Look_Up_Table_table_data[582] = 12'sb001100011110;
  assign Look_Up_Table_table_data[583] = 12'sb001100011111;
  assign Look_Up_Table_table_data[584] = 12'sb001100100000;
  assign Look_Up_Table_table_data[585] = 12'sb001100100001;
  assign Look_Up_Table_table_data[586] = 12'sb001100100001;
  assign Look_Up_Table_table_data[587] = 12'sb001100100010;
  assign Look_Up_Table_table_data[588] = 12'sb001100100011;
  assign Look_Up_Table_table_data[589] = 12'sb001100100100;
  assign Look_Up_Table_table_data[590] = 12'sb001100100101;
  assign Look_Up_Table_table_data[591] = 12'sb001100100110;
  assign Look_Up_Table_table_data[592] = 12'sb001100100111;
  assign Look_Up_Table_table_data[593] = 12'sb001100101000;
  assign Look_Up_Table_table_data[594] = 12'sb001100101001;
  assign Look_Up_Table_table_data[595] = 12'sb001100101010;
  assign Look_Up_Table_table_data[596] = 12'sb001100101011;
  assign Look_Up_Table_table_data[597] = 12'sb001100101100;
  assign Look_Up_Table_table_data[598] = 12'sb001100101101;
  assign Look_Up_Table_table_data[599] = 12'sb001100101110;
  assign Look_Up_Table_table_data[600] = 12'sb001100101111;
  assign Look_Up_Table_table_data[601] = 12'sb001100110000;
  assign Look_Up_Table_table_data[602] = 12'sb001100110001;
  assign Look_Up_Table_table_data[603] = 12'sb001100110010;
  assign Look_Up_Table_table_data[604] = 12'sb001100110011;
  assign Look_Up_Table_table_data[605] = 12'sb001100110100;
  assign Look_Up_Table_table_data[606] = 12'sb001100110101;
  assign Look_Up_Table_table_data[607] = 12'sb001100110110;
  assign Look_Up_Table_table_data[608] = 12'sb001100110111;
  assign Look_Up_Table_table_data[609] = 12'sb001100110111;
  assign Look_Up_Table_table_data[610] = 12'sb001100111000;
  assign Look_Up_Table_table_data[611] = 12'sb001100111001;
  assign Look_Up_Table_table_data[612] = 12'sb001100111010;
  assign Look_Up_Table_table_data[613] = 12'sb001100111011;
  assign Look_Up_Table_table_data[614] = 12'sb001100111100;
  assign Look_Up_Table_table_data[615] = 12'sb001100111101;
  assign Look_Up_Table_table_data[616] = 12'sb001100111110;
  assign Look_Up_Table_table_data[617] = 12'sb001100111111;
  assign Look_Up_Table_table_data[618] = 12'sb001101000000;
  assign Look_Up_Table_table_data[619] = 12'sb001101000001;
  assign Look_Up_Table_table_data[620] = 12'sb001101000010;
  assign Look_Up_Table_table_data[621] = 12'sb001101000011;
  assign Look_Up_Table_table_data[622] = 12'sb001101000011;
  assign Look_Up_Table_table_data[623] = 12'sb001101000100;
  assign Look_Up_Table_table_data[624] = 12'sb001101000101;
  assign Look_Up_Table_table_data[625] = 12'sb001101000110;
  assign Look_Up_Table_table_data[626] = 12'sb001101000111;
  assign Look_Up_Table_table_data[627] = 12'sb001101001000;
  assign Look_Up_Table_table_data[628] = 12'sb001101001001;
  assign Look_Up_Table_table_data[629] = 12'sb001101001010;
  assign Look_Up_Table_table_data[630] = 12'sb001101001011;
  assign Look_Up_Table_table_data[631] = 12'sb001101001100;
  assign Look_Up_Table_table_data[632] = 12'sb001101001100;
  assign Look_Up_Table_table_data[633] = 12'sb001101001101;
  assign Look_Up_Table_table_data[634] = 12'sb001101001110;
  assign Look_Up_Table_table_data[635] = 12'sb001101001111;
  assign Look_Up_Table_table_data[636] = 12'sb001101010000;
  assign Look_Up_Table_table_data[637] = 12'sb001101010001;
  assign Look_Up_Table_table_data[638] = 12'sb001101010010;
  assign Look_Up_Table_table_data[639] = 12'sb001101010011;
  assign Look_Up_Table_table_data[640] = 12'sb001101010011;
  assign Look_Up_Table_table_data[641] = 12'sb001101010100;
  assign Look_Up_Table_table_data[642] = 12'sb001101010101;
  assign Look_Up_Table_table_data[643] = 12'sb001101010110;
  assign Look_Up_Table_table_data[644] = 12'sb001101010111;
  assign Look_Up_Table_table_data[645] = 12'sb001101011000;
  assign Look_Up_Table_table_data[646] = 12'sb001101011001;
  assign Look_Up_Table_table_data[647] = 12'sb001101011010;
  assign Look_Up_Table_table_data[648] = 12'sb001101011010;
  assign Look_Up_Table_table_data[649] = 12'sb001101011011;
  assign Look_Up_Table_table_data[650] = 12'sb001101011100;
  assign Look_Up_Table_table_data[651] = 12'sb001101011101;
  assign Look_Up_Table_table_data[652] = 12'sb001101011110;
  assign Look_Up_Table_table_data[653] = 12'sb001101011111;
  assign Look_Up_Table_table_data[654] = 12'sb001101011111;
  assign Look_Up_Table_table_data[655] = 12'sb001101100000;
  assign Look_Up_Table_table_data[656] = 12'sb001101100001;
  assign Look_Up_Table_table_data[657] = 12'sb001101100010;
  assign Look_Up_Table_table_data[658] = 12'sb001101100011;
  assign Look_Up_Table_table_data[659] = 12'sb001101100100;
  assign Look_Up_Table_table_data[660] = 12'sb001101100101;
  assign Look_Up_Table_table_data[661] = 12'sb001101100101;
  assign Look_Up_Table_table_data[662] = 12'sb001101100110;
  assign Look_Up_Table_table_data[663] = 12'sb001101100111;
  assign Look_Up_Table_table_data[664] = 12'sb001101101000;
  assign Look_Up_Table_table_data[665] = 12'sb001101101001;
  assign Look_Up_Table_table_data[666] = 12'sb001101101001;
  assign Look_Up_Table_table_data[667] = 12'sb001101101010;
  assign Look_Up_Table_table_data[668] = 12'sb001101101011;
  assign Look_Up_Table_table_data[669] = 12'sb001101101100;
  assign Look_Up_Table_table_data[670] = 12'sb001101101101;
  assign Look_Up_Table_table_data[671] = 12'sb001101101110;
  assign Look_Up_Table_table_data[672] = 12'sb001101101110;
  assign Look_Up_Table_table_data[673] = 12'sb001101101111;
  assign Look_Up_Table_table_data[674] = 12'sb001101110000;
  assign Look_Up_Table_table_data[675] = 12'sb001101110001;
  assign Look_Up_Table_table_data[676] = 12'sb001101110010;
  assign Look_Up_Table_table_data[677] = 12'sb001101110010;
  assign Look_Up_Table_table_data[678] = 12'sb001101110011;
  assign Look_Up_Table_table_data[679] = 12'sb001101110100;
  assign Look_Up_Table_table_data[680] = 12'sb001101110101;
  assign Look_Up_Table_table_data[681] = 12'sb001101110110;
  assign Look_Up_Table_table_data[682] = 12'sb001101110110;
  assign Look_Up_Table_table_data[683] = 12'sb001101110111;
  assign Look_Up_Table_table_data[684] = 12'sb001101111000;
  assign Look_Up_Table_table_data[685] = 12'sb001101111001;
  assign Look_Up_Table_table_data[686] = 12'sb001101111001;
  assign Look_Up_Table_table_data[687] = 12'sb001101111010;
  assign Look_Up_Table_table_data[688] = 12'sb001101111011;
  assign Look_Up_Table_table_data[689] = 12'sb001101111100;
  assign Look_Up_Table_table_data[690] = 12'sb001101111101;
  assign Look_Up_Table_table_data[691] = 12'sb001101111101;
  assign Look_Up_Table_table_data[692] = 12'sb001101111110;
  assign Look_Up_Table_table_data[693] = 12'sb001101111111;
  assign Look_Up_Table_table_data[694] = 12'sb001110000000;
  assign Look_Up_Table_table_data[695] = 12'sb001110000000;
  assign Look_Up_Table_table_data[696] = 12'sb001110000001;
  assign Look_Up_Table_table_data[697] = 12'sb001110000010;
  assign Look_Up_Table_table_data[698] = 12'sb001110000011;
  assign Look_Up_Table_table_data[699] = 12'sb001110000011;
  assign Look_Up_Table_table_data[700] = 12'sb001110000100;
  assign Look_Up_Table_table_data[701] = 12'sb001110000101;
  assign Look_Up_Table_table_data[702] = 12'sb001110000110;
  assign Look_Up_Table_table_data[703] = 12'sb001110000110;
  assign Look_Up_Table_table_data[704] = 12'sb001110000111;
  assign Look_Up_Table_table_data[705] = 12'sb001110001000;
  assign Look_Up_Table_table_data[706] = 12'sb001110001001;
  assign Look_Up_Table_table_data[707] = 12'sb001110001001;
  assign Look_Up_Table_table_data[708] = 12'sb001110001010;
  assign Look_Up_Table_table_data[709] = 12'sb001110001011;
  assign Look_Up_Table_table_data[710] = 12'sb001110001011;
  assign Look_Up_Table_table_data[711] = 12'sb001110001100;
  assign Look_Up_Table_table_data[712] = 12'sb001110001101;
  assign Look_Up_Table_table_data[713] = 12'sb001110001110;
  assign Look_Up_Table_table_data[714] = 12'sb001110001110;
  assign Look_Up_Table_table_data[715] = 12'sb001110001111;
  assign Look_Up_Table_table_data[716] = 12'sb001110010000;
  assign Look_Up_Table_table_data[717] = 12'sb001110010001;
  assign Look_Up_Table_table_data[718] = 12'sb001110010001;
  assign Look_Up_Table_table_data[719] = 12'sb001110010010;
  assign Look_Up_Table_table_data[720] = 12'sb001110010011;
  assign Look_Up_Table_table_data[721] = 12'sb001110010011;
  assign Look_Up_Table_table_data[722] = 12'sb001110010100;
  assign Look_Up_Table_table_data[723] = 12'sb001110010101;
  assign Look_Up_Table_table_data[724] = 12'sb001110010101;
  assign Look_Up_Table_table_data[725] = 12'sb001110010110;
  assign Look_Up_Table_table_data[726] = 12'sb001110010111;
  assign Look_Up_Table_table_data[727] = 12'sb001110011000;
  assign Look_Up_Table_table_data[728] = 12'sb001110011000;
  assign Look_Up_Table_table_data[729] = 12'sb001110011001;
  assign Look_Up_Table_table_data[730] = 12'sb001110011010;
  assign Look_Up_Table_table_data[731] = 12'sb001110011010;
  assign Look_Up_Table_table_data[732] = 12'sb001110011011;
  assign Look_Up_Table_table_data[733] = 12'sb001110011100;
  assign Look_Up_Table_table_data[734] = 12'sb001110011100;
  assign Look_Up_Table_table_data[735] = 12'sb001110011101;
  assign Look_Up_Table_table_data[736] = 12'sb001110011110;
  assign Look_Up_Table_table_data[737] = 12'sb001110011110;
  assign Look_Up_Table_table_data[738] = 12'sb001110011111;
  assign Look_Up_Table_table_data[739] = 12'sb001110100000;
  assign Look_Up_Table_table_data[740] = 12'sb001110100000;
  assign Look_Up_Table_table_data[741] = 12'sb001110100001;
  assign Look_Up_Table_table_data[742] = 12'sb001110100010;
  assign Look_Up_Table_table_data[743] = 12'sb001110100010;
  assign Look_Up_Table_table_data[744] = 12'sb001110100011;
  assign Look_Up_Table_table_data[745] = 12'sb001110100100;
  assign Look_Up_Table_table_data[746] = 12'sb001110100100;
  assign Look_Up_Table_table_data[747] = 12'sb001110100101;
  assign Look_Up_Table_table_data[748] = 12'sb001110100110;
  assign Look_Up_Table_table_data[749] = 12'sb001110100110;
  assign Look_Up_Table_table_data[750] = 12'sb001110100111;
  assign Look_Up_Table_table_data[751] = 12'sb001110100111;
  assign Look_Up_Table_table_data[752] = 12'sb001110101000;
  assign Look_Up_Table_table_data[753] = 12'sb001110101001;
  assign Look_Up_Table_table_data[754] = 12'sb001110101001;
  assign Look_Up_Table_table_data[755] = 12'sb001110101010;
  assign Look_Up_Table_table_data[756] = 12'sb001110101011;
  assign Look_Up_Table_table_data[757] = 12'sb001110101011;
  assign Look_Up_Table_table_data[758] = 12'sb001110101100;
  assign Look_Up_Table_table_data[759] = 12'sb001110101101;
  assign Look_Up_Table_table_data[760] = 12'sb001110101101;
  assign Look_Up_Table_table_data[761] = 12'sb001110101110;
  assign Look_Up_Table_table_data[762] = 12'sb001110101110;
  assign Look_Up_Table_table_data[763] = 12'sb001110101111;
  assign Look_Up_Table_table_data[764] = 12'sb001110110000;
  assign Look_Up_Table_table_data[765] = 12'sb001110110000;
  assign Look_Up_Table_table_data[766] = 12'sb001110110001;
  assign Look_Up_Table_table_data[767] = 12'sb001110110001;
  assign Look_Up_Table_table_data[768] = 12'sb001110110010;
  assign Look_Up_Table_table_data[769] = 12'sb001110110011;
  assign Look_Up_Table_table_data[770] = 12'sb001110110011;
  assign Look_Up_Table_table_data[771] = 12'sb001110110100;
  assign Look_Up_Table_table_data[772] = 12'sb001110110100;
  assign Look_Up_Table_table_data[773] = 12'sb001110110101;
  assign Look_Up_Table_table_data[774] = 12'sb001110110110;
  assign Look_Up_Table_table_data[775] = 12'sb001110110110;
  assign Look_Up_Table_table_data[776] = 12'sb001110110111;
  assign Look_Up_Table_table_data[777] = 12'sb001110110111;
  assign Look_Up_Table_table_data[778] = 12'sb001110111000;
  assign Look_Up_Table_table_data[779] = 12'sb001110111000;
  assign Look_Up_Table_table_data[780] = 12'sb001110111001;
  assign Look_Up_Table_table_data[781] = 12'sb001110111010;
  assign Look_Up_Table_table_data[782] = 12'sb001110111010;
  assign Look_Up_Table_table_data[783] = 12'sb001110111011;
  assign Look_Up_Table_table_data[784] = 12'sb001110111011;
  assign Look_Up_Table_table_data[785] = 12'sb001110111100;
  assign Look_Up_Table_table_data[786] = 12'sb001110111100;
  assign Look_Up_Table_table_data[787] = 12'sb001110111101;
  assign Look_Up_Table_table_data[788] = 12'sb001110111110;
  assign Look_Up_Table_table_data[789] = 12'sb001110111110;
  assign Look_Up_Table_table_data[790] = 12'sb001110111111;
  assign Look_Up_Table_table_data[791] = 12'sb001110111111;
  assign Look_Up_Table_table_data[792] = 12'sb001111000000;
  assign Look_Up_Table_table_data[793] = 12'sb001111000000;
  assign Look_Up_Table_table_data[794] = 12'sb001111000001;
  assign Look_Up_Table_table_data[795] = 12'sb001111000001;
  assign Look_Up_Table_table_data[796] = 12'sb001111000010;
  assign Look_Up_Table_table_data[797] = 12'sb001111000010;
  assign Look_Up_Table_table_data[798] = 12'sb001111000011;
  assign Look_Up_Table_table_data[799] = 12'sb001111000100;
  assign Look_Up_Table_table_data[800] = 12'sb001111000100;
  assign Look_Up_Table_table_data[801] = 12'sb001111000101;
  assign Look_Up_Table_table_data[802] = 12'sb001111000101;
  assign Look_Up_Table_table_data[803] = 12'sb001111000110;
  assign Look_Up_Table_table_data[804] = 12'sb001111000110;
  assign Look_Up_Table_table_data[805] = 12'sb001111000111;
  assign Look_Up_Table_table_data[806] = 12'sb001111000111;
  assign Look_Up_Table_table_data[807] = 12'sb001111001000;
  assign Look_Up_Table_table_data[808] = 12'sb001111001000;
  assign Look_Up_Table_table_data[809] = 12'sb001111001001;
  assign Look_Up_Table_table_data[810] = 12'sb001111001001;
  assign Look_Up_Table_table_data[811] = 12'sb001111001010;
  assign Look_Up_Table_table_data[812] = 12'sb001111001010;
  assign Look_Up_Table_table_data[813] = 12'sb001111001011;
  assign Look_Up_Table_table_data[814] = 12'sb001111001011;
  assign Look_Up_Table_table_data[815] = 12'sb001111001100;
  assign Look_Up_Table_table_data[816] = 12'sb001111001100;
  assign Look_Up_Table_table_data[817] = 12'sb001111001101;
  assign Look_Up_Table_table_data[818] = 12'sb001111001101;
  assign Look_Up_Table_table_data[819] = 12'sb001111001110;
  assign Look_Up_Table_table_data[820] = 12'sb001111001110;
  assign Look_Up_Table_table_data[821] = 12'sb001111001111;
  assign Look_Up_Table_table_data[822] = 12'sb001111001111;
  assign Look_Up_Table_table_data[823] = 12'sb001111010000;
  assign Look_Up_Table_table_data[824] = 12'sb001111010000;
  assign Look_Up_Table_table_data[825] = 12'sb001111010001;
  assign Look_Up_Table_table_data[826] = 12'sb001111010001;
  assign Look_Up_Table_table_data[827] = 12'sb001111010001;
  assign Look_Up_Table_table_data[828] = 12'sb001111010010;
  assign Look_Up_Table_table_data[829] = 12'sb001111010010;
  assign Look_Up_Table_table_data[830] = 12'sb001111010011;
  assign Look_Up_Table_table_data[831] = 12'sb001111010011;
  assign Look_Up_Table_table_data[832] = 12'sb001111010100;
  assign Look_Up_Table_table_data[833] = 12'sb001111010100;
  assign Look_Up_Table_table_data[834] = 12'sb001111010101;
  assign Look_Up_Table_table_data[835] = 12'sb001111010101;
  assign Look_Up_Table_table_data[836] = 12'sb001111010110;
  assign Look_Up_Table_table_data[837] = 12'sb001111010110;
  assign Look_Up_Table_table_data[838] = 12'sb001111010110;
  assign Look_Up_Table_table_data[839] = 12'sb001111010111;
  assign Look_Up_Table_table_data[840] = 12'sb001111010111;
  assign Look_Up_Table_table_data[841] = 12'sb001111011000;
  assign Look_Up_Table_table_data[842] = 12'sb001111011000;
  assign Look_Up_Table_table_data[843] = 12'sb001111011001;
  assign Look_Up_Table_table_data[844] = 12'sb001111011001;
  assign Look_Up_Table_table_data[845] = 12'sb001111011001;
  assign Look_Up_Table_table_data[846] = 12'sb001111011010;
  assign Look_Up_Table_table_data[847] = 12'sb001111011010;
  assign Look_Up_Table_table_data[848] = 12'sb001111011011;
  assign Look_Up_Table_table_data[849] = 12'sb001111011011;
  assign Look_Up_Table_table_data[850] = 12'sb001111011100;
  assign Look_Up_Table_table_data[851] = 12'sb001111011100;
  assign Look_Up_Table_table_data[852] = 12'sb001111011100;
  assign Look_Up_Table_table_data[853] = 12'sb001111011101;
  assign Look_Up_Table_table_data[854] = 12'sb001111011101;
  assign Look_Up_Table_table_data[855] = 12'sb001111011110;
  assign Look_Up_Table_table_data[856] = 12'sb001111011110;
  assign Look_Up_Table_table_data[857] = 12'sb001111011110;
  assign Look_Up_Table_table_data[858] = 12'sb001111011111;
  assign Look_Up_Table_table_data[859] = 12'sb001111011111;
  assign Look_Up_Table_table_data[860] = 12'sb001111100000;
  assign Look_Up_Table_table_data[861] = 12'sb001111100000;
  assign Look_Up_Table_table_data[862] = 12'sb001111100000;
  assign Look_Up_Table_table_data[863] = 12'sb001111100001;
  assign Look_Up_Table_table_data[864] = 12'sb001111100001;
  assign Look_Up_Table_table_data[865] = 12'sb001111100010;
  assign Look_Up_Table_table_data[866] = 12'sb001111100010;
  assign Look_Up_Table_table_data[867] = 12'sb001111100010;
  assign Look_Up_Table_table_data[868] = 12'sb001111100011;
  assign Look_Up_Table_table_data[869] = 12'sb001111100011;
  assign Look_Up_Table_table_data[870] = 12'sb001111100011;
  assign Look_Up_Table_table_data[871] = 12'sb001111100100;
  assign Look_Up_Table_table_data[872] = 12'sb001111100100;
  assign Look_Up_Table_table_data[873] = 12'sb001111100100;
  assign Look_Up_Table_table_data[874] = 12'sb001111100101;
  assign Look_Up_Table_table_data[875] = 12'sb001111100101;
  assign Look_Up_Table_table_data[876] = 12'sb001111100110;
  assign Look_Up_Table_table_data[877] = 12'sb001111100110;
  assign Look_Up_Table_table_data[878] = 12'sb001111100110;
  assign Look_Up_Table_table_data[879] = 12'sb001111100111;
  assign Look_Up_Table_table_data[880] = 12'sb001111100111;
  assign Look_Up_Table_table_data[881] = 12'sb001111100111;
  assign Look_Up_Table_table_data[882] = 12'sb001111101000;
  assign Look_Up_Table_table_data[883] = 12'sb001111101000;
  assign Look_Up_Table_table_data[884] = 12'sb001111101000;
  assign Look_Up_Table_table_data[885] = 12'sb001111101001;
  assign Look_Up_Table_table_data[886] = 12'sb001111101001;
  assign Look_Up_Table_table_data[887] = 12'sb001111101001;
  assign Look_Up_Table_table_data[888] = 12'sb001111101010;
  assign Look_Up_Table_table_data[889] = 12'sb001111101010;
  assign Look_Up_Table_table_data[890] = 12'sb001111101010;
  assign Look_Up_Table_table_data[891] = 12'sb001111101011;
  assign Look_Up_Table_table_data[892] = 12'sb001111101011;
  assign Look_Up_Table_table_data[893] = 12'sb001111101011;
  assign Look_Up_Table_table_data[894] = 12'sb001111101011;
  assign Look_Up_Table_table_data[895] = 12'sb001111101100;
  assign Look_Up_Table_table_data[896] = 12'sb001111101100;
  assign Look_Up_Table_table_data[897] = 12'sb001111101100;
  assign Look_Up_Table_table_data[898] = 12'sb001111101101;
  assign Look_Up_Table_table_data[899] = 12'sb001111101101;
  assign Look_Up_Table_table_data[900] = 12'sb001111101101;
  assign Look_Up_Table_table_data[901] = 12'sb001111101110;
  assign Look_Up_Table_table_data[902] = 12'sb001111101110;
  assign Look_Up_Table_table_data[903] = 12'sb001111101110;
  assign Look_Up_Table_table_data[904] = 12'sb001111101110;
  assign Look_Up_Table_table_data[905] = 12'sb001111101111;
  assign Look_Up_Table_table_data[906] = 12'sb001111101111;
  assign Look_Up_Table_table_data[907] = 12'sb001111101111;
  assign Look_Up_Table_table_data[908] = 12'sb001111110000;
  assign Look_Up_Table_table_data[909] = 12'sb001111110000;
  assign Look_Up_Table_table_data[910] = 12'sb001111110000;
  assign Look_Up_Table_table_data[911] = 12'sb001111110000;
  assign Look_Up_Table_table_data[912] = 12'sb001111110001;
  assign Look_Up_Table_table_data[913] = 12'sb001111110001;
  assign Look_Up_Table_table_data[914] = 12'sb001111110001;
  assign Look_Up_Table_table_data[915] = 12'sb001111110001;
  assign Look_Up_Table_table_data[916] = 12'sb001111110010;
  assign Look_Up_Table_table_data[917] = 12'sb001111110010;
  assign Look_Up_Table_table_data[918] = 12'sb001111110010;
  assign Look_Up_Table_table_data[919] = 12'sb001111110010;
  assign Look_Up_Table_table_data[920] = 12'sb001111110011;
  assign Look_Up_Table_table_data[921] = 12'sb001111110011;
  assign Look_Up_Table_table_data[922] = 12'sb001111110011;
  assign Look_Up_Table_table_data[923] = 12'sb001111110011;
  assign Look_Up_Table_table_data[924] = 12'sb001111110100;
  assign Look_Up_Table_table_data[925] = 12'sb001111110100;
  assign Look_Up_Table_table_data[926] = 12'sb001111110100;
  assign Look_Up_Table_table_data[927] = 12'sb001111110100;
  assign Look_Up_Table_table_data[928] = 12'sb001111110101;
  assign Look_Up_Table_table_data[929] = 12'sb001111110101;
  assign Look_Up_Table_table_data[930] = 12'sb001111110101;
  assign Look_Up_Table_table_data[931] = 12'sb001111110101;
  assign Look_Up_Table_table_data[932] = 12'sb001111110110;
  assign Look_Up_Table_table_data[933] = 12'sb001111110110;
  assign Look_Up_Table_table_data[934] = 12'sb001111110110;
  assign Look_Up_Table_table_data[935] = 12'sb001111110110;
  assign Look_Up_Table_table_data[936] = 12'sb001111110110;
  assign Look_Up_Table_table_data[937] = 12'sb001111110111;
  assign Look_Up_Table_table_data[938] = 12'sb001111110111;
  assign Look_Up_Table_table_data[939] = 12'sb001111110111;
  assign Look_Up_Table_table_data[940] = 12'sb001111110111;
  assign Look_Up_Table_table_data[941] = 12'sb001111110111;
  assign Look_Up_Table_table_data[942] = 12'sb001111111000;
  assign Look_Up_Table_table_data[943] = 12'sb001111111000;
  assign Look_Up_Table_table_data[944] = 12'sb001111111000;
  assign Look_Up_Table_table_data[945] = 12'sb001111111000;
  assign Look_Up_Table_table_data[946] = 12'sb001111111000;
  assign Look_Up_Table_table_data[947] = 12'sb001111111001;
  assign Look_Up_Table_table_data[948] = 12'sb001111111001;
  assign Look_Up_Table_table_data[949] = 12'sb001111111001;
  assign Look_Up_Table_table_data[950] = 12'sb001111111001;
  assign Look_Up_Table_table_data[951] = 12'sb001111111001;
  assign Look_Up_Table_table_data[952] = 12'sb001111111001;
  assign Look_Up_Table_table_data[953] = 12'sb001111111010;
  assign Look_Up_Table_table_data[954] = 12'sb001111111010;
  assign Look_Up_Table_table_data[955] = 12'sb001111111010;
  assign Look_Up_Table_table_data[956] = 12'sb001111111010;
  assign Look_Up_Table_table_data[957] = 12'sb001111111010;
  assign Look_Up_Table_table_data[958] = 12'sb001111111010;
  assign Look_Up_Table_table_data[959] = 12'sb001111111011;
  assign Look_Up_Table_table_data[960] = 12'sb001111111011;
  assign Look_Up_Table_table_data[961] = 12'sb001111111011;
  assign Look_Up_Table_table_data[962] = 12'sb001111111011;
  assign Look_Up_Table_table_data[963] = 12'sb001111111011;
  assign Look_Up_Table_table_data[964] = 12'sb001111111011;
  assign Look_Up_Table_table_data[965] = 12'sb001111111011;
  assign Look_Up_Table_table_data[966] = 12'sb001111111100;
  assign Look_Up_Table_table_data[967] = 12'sb001111111100;
  assign Look_Up_Table_table_data[968] = 12'sb001111111100;
  assign Look_Up_Table_table_data[969] = 12'sb001111111100;
  assign Look_Up_Table_table_data[970] = 12'sb001111111100;
  assign Look_Up_Table_table_data[971] = 12'sb001111111100;
  assign Look_Up_Table_table_data[972] = 12'sb001111111100;
  assign Look_Up_Table_table_data[973] = 12'sb001111111100;
  assign Look_Up_Table_table_data[974] = 12'sb001111111101;
  assign Look_Up_Table_table_data[975] = 12'sb001111111101;
  assign Look_Up_Table_table_data[976] = 12'sb001111111101;
  assign Look_Up_Table_table_data[977] = 12'sb001111111101;
  assign Look_Up_Table_table_data[978] = 12'sb001111111101;
  assign Look_Up_Table_table_data[979] = 12'sb001111111101;
  assign Look_Up_Table_table_data[980] = 12'sb001111111101;
  assign Look_Up_Table_table_data[981] = 12'sb001111111101;
  assign Look_Up_Table_table_data[982] = 12'sb001111111101;
  assign Look_Up_Table_table_data[983] = 12'sb001111111110;
  assign Look_Up_Table_table_data[984] = 12'sb001111111110;
  assign Look_Up_Table_table_data[985] = 12'sb001111111110;
  assign Look_Up_Table_table_data[986] = 12'sb001111111110;
  assign Look_Up_Table_table_data[987] = 12'sb001111111110;
  assign Look_Up_Table_table_data[988] = 12'sb001111111110;
  assign Look_Up_Table_table_data[989] = 12'sb001111111110;
  assign Look_Up_Table_table_data[990] = 12'sb001111111110;
  assign Look_Up_Table_table_data[991] = 12'sb001111111110;
  assign Look_Up_Table_table_data[992] = 12'sb001111111110;
  assign Look_Up_Table_table_data[993] = 12'sb001111111110;
  assign Look_Up_Table_table_data[994] = 12'sb001111111110;
  assign Look_Up_Table_table_data[995] = 12'sb001111111111;
  assign Look_Up_Table_table_data[996] = 12'sb001111111111;
  assign Look_Up_Table_table_data[997] = 12'sb001111111111;
  assign Look_Up_Table_table_data[998] = 12'sb001111111111;
  assign Look_Up_Table_table_data[999] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1000] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1001] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1002] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1003] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1004] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1005] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1006] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1007] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1008] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1009] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1010] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1011] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1012] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1013] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1014] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1015] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1016] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1017] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1018] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1019] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1020] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1021] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1022] = 12'sb001111111111;
  assign Look_Up_Table_table_data[1023] = 12'sb010000000000;
  assign Look_Up_Table_k = (CastU16En2_out1 == 10'b0000000000 ? 10'b0000000000 :
              (CastU16En2_out1 == 10'b1111111111 ? 10'b1111111111 :
              CastU16En2_out1));
  assign Look_Up_Table_out1 = Look_Up_Table_table_data[Look_Up_Table_k];



  always @(posedge clk)
    begin : Unit_Delay_process
      if (kill == 1'b1) begin
        Unit_Delay_out1 <= 12'sb000000000000;
      end
      else begin
        Unit_Delay_out1 <= Look_Up_Table_out1;
      end
    end



  assign Negate_cast = {Unit_Delay_out1[11], Unit_Delay_out1};
  assign Negate_cast_1 =  - (Negate_cast);
  assign Negate_out1 = Negate_cast_1[11:0];



  assign Cosine = (RAMDelayBalance_out1 == 8'b00000000 ? Negate_out1 :
              Unit_Delay_out1);



  assign x = Cosine;

endmodule  // cos_add_1bit1

