// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/exponent/exponent.v
// Created: 2024-05-31 10:33:15
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: exponent
// Source Path: exponent
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module exponent
          (clk,
           kill,
           freq,
           exp_out_re,
           exp_out_im);


  input   clk;
  input   kill;
  input   signed [11:0] freq;  // sfix12_En12
  output  signed [11:0] exp_out_re;  // sfix12_En10
  output  signed [11:0] exp_out_im;  // sfix12_En10


  wire signed [9:0] nco_out1;  // sfix10_En10
  wire signed [11:0] exponent_out1_re;  // sfix12_En10
  wire signed [11:0] exponent_out1_im;  // sfix12_En10


  nco u_nco (.clk(clk),
             .kill(kill),
             .nco_in(freq),  // sfix12_En12
             .nco_out(nco_out1)  // sfix10_En10
             );

  exponent_block u_exponent (.clk(clk),
                             .kill(kill),
                             .phase(nco_out1),  // sfix10_En10
                             .exp_re(exponent_out1_re),  // sfix12_En10
                             .exp_im(exponent_out1_im)  // sfix12_En10
                             );

  assign exp_out_re = exponent_out1_re;

  assign exp_out_im = exponent_out1_im;

endmodule  // exponent

