// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/exponent/nco.v
// Created: 2024-05-31 10:33:15
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nco
// Source Path: exponent/nco
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nco
          (clk,
           kill,
           nco_in,
           nco_out);


  input   clk;
  input   kill;
  input   signed [11:0] nco_in;  // sfix12_En12
  output  signed [9:0] nco_out;  // sfix10_En10


  wire signed [9:0] Add_out1;  // sfix10_En10
  reg signed [9:0] Unit_Delay_out1;  // sfix10_En10
  wire signed [12:0] Add_add_cast;  // sfix13_En12
  wire signed [12:0] Add_add_cast_1;  // sfix13_En12
  wire signed [12:0] Add_add_temp;  // sfix13_En12


  always @(posedge clk)
    begin : Unit_Delay_process
      if (kill == 1'b1) begin
        Unit_Delay_out1 <= 10'sb0000000000;
      end
      else begin
        Unit_Delay_out1 <= Add_out1;
      end
    end



  assign Add_add_cast = {nco_in[11], nco_in};
  assign Add_add_cast_1 = {Unit_Delay_out1[9], {Unit_Delay_out1, 2'b00}};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1 = Add_add_temp[11:2];



  assign nco_out = Add_out1;

endmodule  // nco

